const Config = {
  LIMIT: "APP_LIMIT",
  PERSIST_SECRET_KEY: "APP_REDUX_PERSIST_STORE_KEY",
  ENVIRONMENT: "APP_ENV",
  ENVIRONMENTS: {
    LOCAL: {
      API_URL: "APP_API_URL",
      GOOGLE_API_KEY: "APP_GOOGLE_API_KEY",
      FIREBASE_API_KEY: "APP_FIREBASE_API_KEY",
      FIREBASE_AUTH_DOMAIN: "APP_FIREBASE_AUTH_DOMAIN",
      FIREBASE_PROJECT_ID: "APP_FIREBASE_PROJECT_ID",
      FIREBASE_SENDER_ID: "APP_FIREBASE_SENDER_ID",
      FIREBASE_APP_ID: "APP_FIREBASE_APP_ID",
    },
    DEVELOPMENT: {
      API_URL: "APP_API_URL",
      GOOGLE_API_KEY: "APP_GOOGLE_API_KEY",
      FIREBASE_API_KEY: "APP_FIREBASE_API_KEY",
      FIREBASE_AUTH_DOMAIN: "APP_FIREBASE_AUTH_DOMAIN",
      FIREBASE_PROJECT_ID: "APP_FIREBASE_PROJECT_ID",
      FIREBASE_SENDER_ID: "APP_FIREBASE_SENDER_ID",
      FIREBASE_APP_ID: "APP_FIREBASE_APP_ID",
    },
    STAGING: {
      API_URL: "APP_API_URL",
      GOOGLE_API_KEY: "APP_GOOGLE_API_KEY",
      FIREBASE_API_KEY: "APP_FIREBASE_API_KEY",
      FIREBASE_AUTH_DOMAIN: "APP_FIREBASE_AUTH_DOMAIN",
      FIREBASE_PROJECT_ID: "APP_FIREBASE_PROJECT_ID",
      FIREBASE_SENDER_ID: "APP_FIREBASE_SENDER_ID",
      FIREBASE_APP_ID: "APP_FIREBASE_APP_ID",
    },
    PRODUCTION: {
      API_URL: "APP_API_URL",
      GOOGLE_API_KEY: "APP_GOOGLE_API_KEY",
      FIREBASE_API_KEY: "APP_FIREBASE_API_KEY",
      FIREBASE_AUTH_DOMAIN: "APP_FIREBASE_AUTH_DOMAIN",
      FIREBASE_PROJECT_ID: "APP_FIREBASE_PROJECT_ID",
      FIREBASE_SENDER_ID: "APP_FIREBASE_SENDER_ID",
      FIREBASE_APP_ID: "APP_FIREBASE_APP_ID",
    },
  },
};

Config.env = () => {
  return Config.ENVIRONMENTS[Config.ENVIRONMENT];
};

export default Config;
